### ISSUE TITLE
Support more complex text source expressions

### ISSUE THREAD

**Issue by ianthetechie** [stadiamaps/cartogrify#7]
Mapbox has a simple format language for specifying a text label in terms of multiple fields (it's very much like a Python f-string). Currently we just ignore this unless the source is just a single field. We shouldn't ;)

**Comment by nvkelso** [comment]
https://tangrams.readthedocs.io/en/master/Syntax-Reference/draw/#text_source

**Comment by ianthetechie** [comment]
Thanks! I thought this was the right approach but didn't know these were *literally* JavaScript functions. That makes the implementation pretty easy.
